#@TYPE: Machine
#@NAME: phyboard-rigel-am67xx-1
#@DESCRIPTION: PHYTEC phyBOARD Rigel AM67x, HS-FS
#@ARTICLENUMBERS: PCM-080.A0

require conf/machine/phyboard-rigel-am67xx-1.conf

KERNEL_OVERLAYS_PHYTEC:append = " \
	ti/k3-am6754-phyboard-rigel-x37-mcu-spi1.dtbo \
"
