FILESEXTRAPATHS:prepend := "${THISDIR}/files:"

SRC_URI:append:phyboard-electra= " \
    file://0001-electra-redundant-bootloader-support-added.patch \
"

# build SPI NOR-specific bootloader binaries
do_compile:append:phyboard-electra-am64xx-2() {
    # 1. Backup the primary (MMC) binaries generated by the standard pass. These have the default env
    cp ${B}/tispl.bin ${B}/tispl-emmc.bin
    cp ${B}/u-boot.img ${B}/u-boot-emmc.img

    oe_runmake -C ${S} O=${B} phycore_am64x_a53_spi_defconfig
    oe_runmake -C ${S} O=${B}

    # 3. Save the resulting SPI binaries. These have a customized env to serve as the fallback/recovery bootloader.
    cp ${B}/tispl.bin ${B}/tispl-spi.bin
    cp ${B}/u-boot.img ${B}/u-boot-spi.img

    # 4. Restore the primary (MMC) binaries and configuration 
    # so WIC/Partup packaging uses the standard eMMC binaries downstream
    cp ${B}/tispl-emmc.bin ${B}/tispl.bin
    cp ${B}/u-boot-emmc.img ${B}/u-boot.img
    oe_runmake -C ${S} O=${B} phycore_am64x_a53_defconfig
}

do_deploy:append:phyboard-electra-am64xx-2() {
    # 5. Deploy the secondary SPI binaries alongside the standard ones
    install -m 644 ${B}/tispl-spi.bin ${DEPLOYDIR}/tispl-spi.bin
    install -m 644 ${B}/u-boot-spi.img ${DEPLOYDIR}/u-boot-spi.img
}
